urls.py
from django.urls import path
from django.contrib.auth import views
from JApp.forms.main import *
from JApp.views.main import *
from django.urls import reverse_lazy


app_name = 'JApp'
urlpatterns = [
    # Main views
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('dashbaord/', DashboardView.as_view(), name='dashboard'),

    # Custom authentication patterns
    path(
        'accounts/login/',
        views.LoginView.as_view(
            form_class=StyledAuthenticationForm,
            template_name='JApp/authentication/login.html',
            extra_context={
                'signup_form': StyledUserCreationForm()
            }
        ),
        name='login'
    ),
    path(
        'accounts/register/',
        UserCreationView.as_view(),
        name='register'
    ),
    path(
        'accounts/<int:id>/edit/',
        UserEditView.as_view(),
        name='edit_user'
    ),
    path(
        'accounts/<int:id>/delete/',
        UserDeletionView.as_view(),
        name='delete_user'
    ),
    path(
        'accounts/logout/',
        views.LogoutView.as_view(
            template_name='JApp/authentication/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'accounts/profile/',
        ProfileView.as_view(),
        name='profile'
    ),
    path(
        'accounts/password/change/',
        views.PasswordChangeView.as_view(
            form_class=StyledPasswordChangeForm,
            template_name='JApp/authentication/change_password.html',
            success_url=reverse_lazy('JApp:change_done')
        ),
        name='change_password'
    ),
    path(
        'accounts/password/change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='JApp/authentication/change_done.html'
        ),
        name='change_done'
    ),
    path(
        'accounts/password/reset/',
        views.PasswordResetView.as_view(
            form_class=StyledPasswordResetForm,
            template_name='JApp/authentication/reset_password.html',
            success_url=reverse_lazy('JApp:reset_done')
        ),
        name='reset_password'
    ),
    path(
        'accounts/password/reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='JApp/authentication/reset_done.html'
        ),
        name='reset_done'
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='JApp/authentication/reset_confirm.html',
            form_class=StyledPasswordResetForm,
            success_url=reverse_lazy('JApp:reset_complete')
        ),
        name='reset_confirm'
    ),
    path(
        'accounts/password/reset/complete/',
        views.PasswordResetCompleteView.as_view(
            template_name='JApp/authentication/reset_complete.html',
        ),
        name='reset_complete'
    ),
]

forms/base.py
from django import forms


class StyledModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(StyledModelForm, self).__init__(*args, **kwargs)
        for label in self.fields:
            field = self.fields[label]
            try:
                if field.widget.input_type == 'checkbox' or field.widget.input_type == 'radio':
                    field.widget.attrs['class'] = 'form-check-input'
                elif field.widget.input_type == 'select':
                    field.widget.attrs['class'] = 'form-select'
                    field.widget.attrs['placeholder'] = field.label
                else:
                    field.widget.attrs['class'] = 'form-control'
                    field.widget.attrs['placeholder'] = field.label
            except Exception:
                field.widget.attrs['class'] = 'form-control'
                field.widget.attrs['placeholder'] = field.label

templates/JApp/authentication/base.html
{% extends 'JApp/base/dashboard.html' %}
{% block main_col_width %}9{% endblock %}
{% block panel %}{% endblock %}

templates/JApp/authentication/change_done.html
{% extends 'JApp/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Chnage Done' %}{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:profile' %}">
            {% translate 'Profile' %}
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:change_password' %}">
            {% translate 'Password Change' %}
        </a>
    </li>
    <li class="breadcrumb-item active">
        {% translate 'Done' %}
    </li>
{% endblock %}
{% block content %}
    <div class="p-5 mb-4 rounded-3 border">
        <div class="container-fluid py-5">
            <h1 class="display-1">
                {% translate 'Password change successful' %}
            </h1>
            <p class="fs-4">
                {% translate 'Your password was changed.' %}
            </p>
            <a class="btn btn-primary btn-lg" role="button" href="{% url 'JApp:login' %}">
                {% translate 'Login' %}
            </a>
        </div>
    </div>
{% endblock %}

templates/JApp/authentication/change_password.html
{% extends 'JApp/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Change Password' %}{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:profile' %}">
            {% translate 'Profile' %}
        </a>
    </li>
    <li class="breadcrumb-item active">
        {% translate 'Password Change' %}
    </li>
{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Password Change' %}
    </h1>
    <p>
        {% blocktranslate %}
            Please enter your old password, for security’s sake, and then enter your new password twice so we can verify
            you typed it in correctly.
        {% endblocktranslate %}
    </p>
    {% include 'JApp/includes/utilties/form.html' with form_tag=1 method='post' floating_labels=1 %}
    {% url 'JApp:profile' as url %}
    {% include 'JApp/includes/utilties/submit.html' with reset=1 cancel_url=url %}
{% endblock %}

templates/JApp/authentication/logged_out.html
{% extends 'JApp/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Logged out' %}{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Logged out' %}
    </h1>
    <p class="lead fs-3">
        {% translate 'Thanks for your time.' %}
    </p>
{% endblock %}

templates/JApp/authentication/login.html
{% extends 'JApp/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Login' %}{% endblock %}
{% block content %}
    <h1 class="display-1 text-center">
        {% translate 'Welcome' %}
    </h1>
    <div class="d-flex align-items-center justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-signin-tab" data-bs-toggle="tab"
                            data-bs-target="#nav-signin"
                            type="button" role="tab" aria-controls="nav-signin" aria-selected="true">
                        {% translate 'Log In' %}
                    </button>
                    <button class="nav-link" id="nav-signup-tab" data-bs-toggle="tab" data-bs-target="#nav-signup"
                            type="button" role="tab" aria-controls="nav-signup" aria-selected="false">
                        {% translate 'Register' %}
                    </button>
                </div>
            </nav>
            <div class="card border-top-0" style="border-top-right-radius: 0; border-top-left-radius: 0">
                <div class="card-body">
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-signin" role="tabpanel"
                             aria-labelledby="nav-signin-tab">
                            <h1 class="fs-1 lead text-primary card-title">
                                {% translate 'Log In' %}
                            </h1>
                            {% include 'JApp/includes/utilties/form.html' with form_tag=1 method='post' floating_labels=1 %}
                            {% url 'JApp:index' as url %}
                            {% include 'JApp/includes/utilties/submit.html' with form_id='form' reset=1 cancel_url=url %}
                        </div>
                        <div class="tab-pane fade" id="nav-signup" role="tabpanel" aria-labelledby="nav-signup-tab">
                            <h1 class="fs-1 lead text-primary card-title">
                                {% translate 'Register' %}
                            </h1>
                            {% url 'JApp:register' as action %}
                            {% include 'JApp/includes/utilties/form.html' with form_tag=1 form=signup_form method='post' action=action id='signup_form' floating_labels=1 %}
                            {% include 'JApp/includes/utilties/submit.html' with form_id='signup_form' reset=1 cancel_url=url %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/JApp/authentication/profile.html
{% extends 'JApp/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Profile' %}{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">
        {% translate 'Profile' %}
    </li>
{% endblock %}
{% block content %}
    <div class="p-lg-5 p-3 mb-4 rounded-3 border">
        <div class="container-fluid py-5">
            <h1 class="display-1">
                {% translate 'Welcome ' %}{{ request.user.username }}
            </h1>
            <p class="lead fs-4">
                {% blocktranslate %}
                    Welcome to your profile, here you will find links to edit, delete your account, change and reset
                    your password.
                {% endblocktranslate %}
            </p>
            <div class="d-lg-flex d-grid align-items-center gap-4">
                <a class="btn btn-warning btn-lg d-inline-flex gap-4 text-white"
                   href="{% url 'JApp:edit_user' request.user.id %}">
                    <i class="bi bi-pencil"></i>
                    {% translate 'Edit Account' %}
                </a>
                <a class="btn btn-danger btn-lg d-inline-flex gap-4"
                   href="{% url 'JApp:delete_user' request.user.id %}">
                    <i class="bi bi-trash"></i>
                    {% translate 'Delete Account' %}
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-md-stretch g-4">
        <div class="col-md-6">
            <div class="h-100 p-3 text-white bg-dark rounded-3">
                <h2 class="display-6">
                    {% translate 'Change the password' %}
                </h2>
                <p>
                    {% blocktranslate %}
                        Here you can change your password.
                    {% endblocktranslate %}
                </p>
                <a href="{% url 'JApp:change_password' %}" class="btn btn-outline-light btn-lg d-inline-flex gap-4">
                    <i class="bi bi-key"></i>
                    {% translate 'Change' %}
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-3 border rounded-3">
                <h2 class="display-6">
                    {% translate 'Reset Password' %}
                </h2>
                <p>
                    {% blocktranslate %}
                        Or if you want to reset your password.
                    {% endblocktranslate %}
                </p>
                <a class="btn btn-outline-secondary btn-lg d-inline-flex gap-4" role="button"
                   href="{% url 'JApp:reset_password' %}">
                    <i class="bi bi-lock"></i>
                    {% translate 'Reset' %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/JApp/authentication/reset_complete.html
{% extends 'JApp/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Complete' %}{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:profile' %}">
            {% translate 'Profile' %}
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:reset_password' %}">
            {% translate 'Password Reset' %}
        </a>
    </li>
    <li class="breadcrumb-item">
        {% translate 'Complete' %}
    </li>
{% endblock %}
{% block content %}
    <div class="p-5 border rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-1">
                {% translate 'Password reset complete' %}
            </h1>
            <p class="fs-4">
                {% translate 'Your password has been set. You may go ahead and log in now.' %}
            </p>
            <a class="btn btn-primary btn-lg" role="button" href="{% url 'JApp:login' %}">
                {% translate 'Login' %}
            </a>
        </div>
    </div>
{% endblock %}

templates/JApp/authentication/reset_confirm.html
{% extends 'JApp/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Confirmation' %}{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:profile' %}">
            {% translate 'Profile' %}
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:reset_password' %}">
            {% translate 'Password Reset' %}
        </a>
    </li>
    <li class="breadcrumb-item">
        {% translate 'Confirm' %}
    </li>
{% endblock %}
{% block content %}
    {% if validlink %}
        <h1 class="display-1">
            {% translate 'Password Reset Confirm' %}
        </h1>
        <p>
            {% translate "Please enter your new password twice so we can verify you typed it in correctly." %}
        </p>
        {% include 'JApp/includes/utilties/form.html' with form_tag=1 method='post' floating_labels=1 %}
        {% url 'JApp:profile' as url %}
        {% include 'JApp/includes/utilties/submit.html' with reset=1 cancel_url=url %}
    {% else %}
        <h1 class="display-1">
            {% translate 'The password reset link was invalid!' %}
        </h1>
        <p class="alert alert-danger">
            {% blocktranslate %}
                The password reset link was invalid, possibly because it has already been used. Please request a new
                password reset.
            {% endblocktranslate %}
        </p>
        <a class="btn btn-lg btn-primary" href="{% url 'JApp:reset_password' %}">
            {% translate 'Request Password Reset' %}
        </a>
    {% endif %}
{% endblock %}

templates/JApp/authentication/reset_done.html
{% extends 'JApp/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Done' %}{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:profile' %}">
            {% translate 'Prfile' %}
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:reset_password' %}">
            {% translate 'Password Reset' %}
        </a>
    </li>
    <li class="breadcrumb-item active">
        {% translate 'Done' %}
    </li>
{% endblock %}
{% block content %}
    <div class="p-5 border rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-1">
                {% translate 'Password reset sent' %}
            </h1>
            <p class="fs-4">
                {% blocktranslate %}
                    We’ve emailed you instructions for setting your password, if an account exists with the email you
                    entered. You should receive them shortly. If you don’t receive an email, please make sure you’ve
                    entered the address you registered with, and check your spam folder.
                {% endblocktranslate %}
            </p>
            <a href="{% url 'JApp:login' %}" class="btn btn-primary btn-lg" role="button">
                {% translate 'Login' %}
            </a>
        </div>
    </div>
{% endblock %}

templates/JApp/authentication/reset_password.html
{% extends 'JApp/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Reset Password' %}{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'JApp:profile' %}">
            {% translate 'Profile' %}
        </a>
    </li>
    <li class="breadcrumb-item active">
        {% translate 'Password Reset' %}
    </li>
{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Reset Password' %}
    </h1>
    <p>
        {% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}
    </p>
    {% include 'JApp/includes/utilties/form.html' with form_tag=1 method='post' floating_labels=1 %}
    {% url 'JApp:profile' as url %}
    {% include 'JApp/includes/utilties/submit.html' with reset=1 cancel_url=url %}
{% endblock %}