urls.py
from django.urls import path
from django.contrib.auth import views
from JApp.forms.main import *
from JApp.views.main import *
from django.urls import reverse_lazy


app_name = 'JApp'
urlpatterns = [
    # Main views
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('dashbaord/', DashboardView.as_view(), name='dashboard'),

    # Custom authentication patterns
    path(
        'accounts/login/',
        views.LoginView.as_view(
            form_class=StyledAuthenticationForm,
            template_name='JApp/authentication/login.html',
            extra_context={
                'signup_form': StyledUserCreationForm()
            }
        ),
        name='login'
    ),
    path(
        'accounts/register/',
        UserCreationView.as_view(),
        name='register'
    ),
    path(
        'accounts/<int:id>/edit/',
        UserEditView.as_view(),
        name='edit_user'
    ),
    path(
        'accounts/<int:id>/delete/',
        UserDeletionView.as_view(),
        name='delete_user'
    ),
    path(
        'accounts/logout/',
        views.LogoutView.as_view(
            template_name='JApp/authentication/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'accounts/profile/',
        ProfileView.as_view(),
        name='profile'
    ),
    path(
        'accounts/password/change/',
        views.PasswordChangeView.as_view(
            form_class=StyledPasswordChangeForm,
            template_name='JApp/authentication/change_password.html',
            success_url=reverse_lazy('JApp:change_done')
        ),
        name='change_password'
    ),
    path(
        'accounts/password/change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='JApp/authentication/change_done.html'
        ),
        name='change_done'
    ),
    path(
        'accounts/password/reset/',
        views.PasswordResetView.as_view(
            form_class=StyledPasswordResetForm,
            template_name='JApp/authentication/reset_password.html',
            success_url=reverse_lazy('JApp:reset_done')
        ),
        name='reset_password'
    ),
    path(
        'accounts/password/reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='JApp/authentication/reset_done.html'
        ),
        name='reset_done'
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='JApp/authentication/reset_confirm.html',
            form_class=StyledPasswordResetForm,
            success_url=reverse_lazy('JApp:reset_complete')
        ),
        name='reset_confirm'
    ),
    path(
        'accounts/password/reset/complete/',
        views.PasswordResetCompleteView.as_view(
            template_name='JApp/authentication/reset_complete.html',
        ),
        name='reset_complete'
    ),
]

templates/JApp/includes/components/messages.html
<ul class="list-unstyled mb-0">
    {% for message in messages %}
        <li>
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show d-flex align-items-center gap-4" role="alert">
                <span class="badge bg-{% if message.tags %}{{ message.tags }}{% endif %} rounded-pill">
                    {{ message.tags|capfirst }}
                </span>
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </li>
    {% endfor %}
</ul>

templates/JApp/includes/components/navbar.html
{% load i18n %}
<nav class="navbar navbar-{{ color|default:'dark' }} bg-{{ bg_color|default:'primary' }} navbar-expand-{{ expand_at|default:'lg' }} p-3 rounded-3 shadow">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'JApp:index' %}">
            {% translate 'JApp' %}
        </a>
        <button class="navbar-toggler collapsed p-2 rounded-circle" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    {% url 'JApp:index' as home %}
                    <a class="nav-link{% if request.path == home %} active{% endif %}" href="{{ home }}">
                        <i class="bi bi-house-fill"></i>
                        {% translate 'Home' %}
                    </a>
                </li>
                <li class="nav-item">
                    {% url 'JApp:dashboard' as dashboard %}
                    <a class="nav-link{% if request.path == dashboard %} active{% endif %}" href="{{ dashboard }}">
                        <i class="bi bi-grid-1x2-fill"></i>
                        {% translate 'Dashboard' %}
                    </a>
                </li>
                <li class="nav-item">
                    {% url 'JApp:about' as about %}
                    <a class="nav-link{% if request.path == about %} active{% endif %}"
                       href="{{ about }}">
                        <i class="bi bi-info-circle-fill"></i>
                        {% translate 'About' %}
                    </a>
                </li>
                <li class="nav-item">
                    {% url 'JApp:contact' as contact %}
                    <a class="nav-link{% if request.path == contact %} active{% endif %}"
                       href="{{ contact }}">
                        <i class="bi bi-envelope-fill"></i>
                        {% translate 'Contact' %}
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'JApp:profile' %}">
                        <i class="bi bi-person-circle"></i>
                        {% translate 'Profile' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/youzarsiph/JApp.git">
                        <i class="bi bi-github"></i>
                        {% translate 'Github' %}
                    </a>
                </li>
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'JApp:logout' %}">
                            <i class="bi bi-power"></i>
                            {% translate 'Logout' %}
                        </a>
                    {% else %}
                        <a class="nav-link" href="{% url 'JApp:login' %}">
                            <i class="bi bi-box-arrow-in-right"></i>
                            {% translate 'Login' %}
                        </a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/JApp/includes/components/panel.html
{% load i18n %}
<nav class="navbar navbar-{{ color|default:'dark' }} bg-{{ bg_color|default:'primary' }} navbar-expand-{{ expand_at|default:'lg' }} align-items-lg-start h-100 rounded-3 shadow"
     aria-label="Panel">
    <div class="container-fluid flex-lg-column align-items-lg-start h-100 w-100 justify-content-start gap-4">
        <button class="navbar-toggler rounded-circle p-2" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#panel" aria-controls="panel">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand me-0" href="#">
            {% translate 'Page Content' %}
        </a>
        <div class="offcanvas offcanvas-end text-white bg-{{ bg_color|default:'primary' }} w-100" tabindex="-1"
             id="panel"
             aria-labelledby="panelLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="panelLabel">
                    {% translate 'On this page' %}
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body d-flex flex-column justify-content-between h-100">
                <ul class="navbar-nav flex-lg-column w-100">
                    {% block page_content %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                {% translate 'Introduction' %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                {% translate 'Getting Started' %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                {% translate 'Models' %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                {% translate 'Views' %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                {% translate 'Examples' %}
                            </a>
                        </li>
                    {% endblock %}
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/JApp/includes/components/sidebar.html
{% load i18n %}
<aside class="navbar navbar-{{ color|default:'dark' }} bg-{{ bg_color|default:'primary' }} navbar-expand-{{ expand_at|default:'lg' }} align-items-lg-start h-100 rounded-3 shadow"
     aria-label="Side bar">
    <div class="container-fluid flex-lg-column align-items-lg-start h-100 w-100">
        <button class="navbar-toggler rounded-circle p-2" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#sidebar"
                aria-controls="sidebar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand me-0" href="#">
            {% translate 'Dashboard' %}
        </a>
        <div class="navbar-nav d-lg-none">
            <a class="nav-link px-3 p-lg-2{% if request.path == profile %} active{% endif %}"
               href="{% url 'JApp:profile' %}">
                <i class="bi bi-person-circle"></i>
            </a>
        </div>
        <div class="offcanvas offcanvas-end text-white bg-{{ bg_color|default:'primary' }}" tabindex="-1" id="sidebar"
             aria-labelledby="sidebarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="sidebarLabel">
                    {% translate 'Dashboard' %}
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body d-flex flex-column justify-content-between h-100">
                <ul class="navbar-nav flex-lg-column w-100">
                    <li class="nav-item">
                        {% url 'JApp:dashboard' as dashboard %}
                        <a class="nav-link d-flex gap-4{% if request.path == dashboard %} active{% endif %}"
                           href="{{ dashboard }}">
                            <i class="bi bi-gear-fill"></i>
                            {% translate 'Dashboard' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-flex gap-4" href="#">
                            <i class="bi bi-link"></i>
                            {% translate 'Link' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-flex gap-4 disabled" href="#" aria-disabled="true">
                            <i class="bi bi-slash-circle-fill"></i>
                            {% translate 'Disabled' %}
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav flex-column">
                    <li class="nav-item">
                        {% url 'JApp:profile' as profile %}
                        <a class="nav-link d-flex gap-4{% if request.path == profile %} active{% endif %}"
                           href="{{ profile }}">
                            <i class="bi bi-person-circle"></i>
                            {% translate 'Account' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-flex gap-4" href="{% url 'JApp:logout' %}">
                            <i class="bi bi-power"></i>
                            {% translate 'Log out' %}
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</aside>

{# Collapse navbar #}
{% comment %}
<nav class="navbar navbar-{{ color|default:'dark' }} bg-{{ bg_color|default:'primary' }} navbar-expand-{{ expand_at|default:'lg' }} align-items-lg-start h-100 rounded-3">
    <div class="container flex-lg-column align-items-lg-start h-100 w-100">
        <button class="navbar-toggler rounded-circle p-2" data-bs-toggle="collapse" data-bs-target="#sidebar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand me-0" href="#">
            {% translate 'Dashboard' %}
        </a>
        <ul class="navbar-nav flex-row flex-lg-column order-lg-last mt-lg-auto w-lg-100">
            <li class="nav-item">
                {% url 'JApp:profile' as profile %}
                <a class="nav-link d-flex gap-4 px-3 p-lg-2{% if request.path == profile %} active{% endif %}"
                   href="{{ profile }}">
                    <i class="bi bi-person-circle"></i>
                    <span class="d-none d-lg-inline">
                        {% translate 'Account' %}
                    </span>
                </a>
            </li>
            <li class="nav-item d-none d-lg-block">
                <a class="nav-link d-flex gap-4" href="{% url 'JApp:logout' %}">
                    <i class="bi bi-power"></i>
                    {% translate 'Log out' %}
                </a>
            </li>
        </ul>
        <div class="collapse navbar-collapse mb-auto align-items-lg-start w-100" id="sidebar">
            <ul class="navbar-nav flex-lg-column w-100">
                <li class="nav-item">
                    {% url 'JApp:dashboard' as dashboard %}
                    <a class="nav-link d-flex gap-4{% if request.path == dashboard %} active{% endif %}"
                       href="{{ dashboard }}">
                        <i class="bi bi-house"></i>
                        {% translate 'Home' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex gap-4" href="#">
                        <i class="bi bi-link"></i>
                        {% translate 'Link' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex gap-4" href="#">
                        <i class="bi bi-slash"></i>
                        {% translate 'Disabled' %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endcomment %}